# -*- coding: utf-8 -*-
"""Tutor Inteligente - OFICIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWXR2uD3ltnYX-ylQTj1DdPqNha1ET-8

# **Tutor Inteligente**
*Por Kemilli Nicole Lima e Ana Luíza Ramos*

A ideia da nossa aplicação é auxiliar usuários, tendo como público alvo os estudantes, a entenderem conteúdos que estão com alguma dificuldade ou limitação. O usuário informa a dificuldade em questão e o sistema multi-agente irá fornecer uma breve explicação a respeito do tópico e, além disso, propor links úteis e exercícios que facilitem a compreensão do cliente, com o objetivo de ajudar o aprendizado.

Funcionamento da aplicação: O sistema utiliza agentes colaborativos **(Crew AI)** que interagem e desempenham papéis específicos para atender ao usuário da melhor maneira.
- **Agente Tutor:** O primeiro agente é responsável por identificar o tópico no qual o usuário está em dúvida e gerar uma explicação breve a respeito dele utilizando uma linguagem acessível.
- **Agente Monitor:** Esse agente busca materiais adicionais (livros, vídeos, artigos e PDFs) relacionados ao tópico específico e garante que o nível esteja acessível para o usuário.
- **Agente Instrutor:** O instrutor, por sua vez, vai propor ao usuário exercícios e perguntas sobre o assunto para que seja possível praticar o conteúdo que os agentes tutores e monitores forneceram.
- **Agente Consultor:** O consultor, por sua vez, é responsável por fornecer as respostas dos exercícios propostos pelo instrutor, para que o usuário possa checar se suas respostas estão corretas ou se sua linha de raciocínio está parcialmente correta.

## Importações e Configurações necessárias
"""

# Instalação do Crew AI e das ferramentas que serão utilizadas ao longo da execução
!pip install crewai crewai_tools openai
import os
import openai
from google.colab import userdata
from openai import OpenAI



os.environ["CREWAI_MODEL"] = "gpt-4-turbo"

# Importando o Agente, a Tarefa e a Equipe do Crew AI
from crewai import Agent, Task, Crew

"""## Código"""

# Criação do Agente Tutor, responsável por fornecer um breve resumo ao usuário, com o objetivo de ajudá-lo a entender sobre o conteúdo em questão
tutor = Agent(
    name = "tutor",
    role = "Responsável por apresentar um breve resumo do tópico: {conteudo}",
    goal = "Entregar o resumo ao usuário para ajudá-lo a entender o {conteudo}",
    backstory = "É um tutor qualificado sobre o {conteudo} "
    "Trabalha na criação de resumo sobre o {conteudo} "
    "Fará uma breve pesquisa de informações na internet e coletá-las, agrupando-as em forma de resumo. "
    "Faça questão de explicar o assunto de forma simples para que o usuário entenda o assunto, de maneira dinâmica e didática. "
    "Deve tratar o usuário de forma calorosa e amigável "
    "Não faça suposições sobre o assunto "
    "Resumo não deve conter mais que 200 palavras ",
    tools = [],
    verbose = True
)

# Criação do Agente Monitor, responsável por fornecer materiais complementares ao usuário, como links, artigos e vídeos, com o objetivo de trazer mais informações para facilitar o aprendizado do usuário
monitor = Agent(
    name = "monitor",
    role = "Encontrar materiais complementares que auxiliem no entendimento, como vídeos e plataformas relevantes a respeito do contéudo: {conteudo}",
    goal = "Fornecer materiais adicionais de qualidade a respeito do {conteudo} e direcionar ao usuário",
    tools = [],
    backstory = "Agente especializado em conseguir materiais sobre o {conteudo} "
    "Você deve utilizar como base os dados fornecidos pelo tutor para encontrar os materiais a respeito do {conteudo} "
    "Faça questão que todos os materiais são apenas sobre o {conteudo} "
    "Encontre os materiais que se adequam mais ao {conteudo} "
    "Materiais devem ser fornecidos ao usuário como links para páginas da internet "
    "Materiais devem ser vídeos, pdfs, imagens, páginas da internet "
    "Deve ser agrupado em forma de lista. Não listar mais que 10 ",
    verbose = True
)

# Criação do Agente Instrutor, responsável por criar 5 exercícios práticos personalizados baseados no conteúdo em questão, com o objetivo de fixar as informações
instrutor = Agent(
    name = "Criador de Exercícios",
    role = "Gerar exercícios contextualizados personalizados baseados no tópico: {conteudo}",
    goal = "Oferecer perguntas e desafios ao usuário, de modo que seja possível aprimorar suas habilidades e facilitar o aprendizado a respeito do {conteudo} em questão",
    tools = [],
    backstory = "O agente é especializado no {conteudo} através do que foi coletado por tutor e monitor "
    "Analisar os dados coletados e criar exercícios simples para o usuário "
    "Faça questão de fornecer elementos simples mas que encapsulam bem o assunto "
    "Não faça suposições sobre o assunto "
    "Deve criar em média 8 exercícios contextualizados sobre o assunto, aumentando gradativamente o nível de dificuldade ",
    verbose = True
)

# Criação do Agente Consultor, responsável por fornecer as respostas dos exercícios propostos pelo agente Instrutor, para que o usuário possa conferir sua linha de raciocínio
consultor = Agent(
    name = "Corretor de Exercícios",
    role = "Fornecer o gabarito dos excercícios feitos pelo agente Instrutor a respeito do conteúdo: {conteudo}",
    goal = "Responder de forma correta os exerícios propostos para que o usuário tenha uma forma de conferir se sua linha de raciocínio está correta ao respeito do tópico",
    tools = [],
    backstory = "O agente é especializado no {conteudo} através do que foi coletado por tutor, monitor e exercícios propoostos pelo instrutor "
    "respondendo as perguntas de maneira correta para que o usuário possa ter uma referência do caminho a ser seguido ou, apenas, conferir seu gabarito "
    "Deve fornecer as respostas corretas de forma detalhada "
    "Não faça suposições sobre o assunto",
    verbose = True
)

# Criação da tarefa do agente Tutor, responsável por gerar o resumo do tópico para o usuário
resumir = Task(
    name = "Resumo explicativo a respeito do conteúdo: {conteudo}",
    description = "Buscar informações a respeito do tópico {conteudo} e faz um breve resumo do conteúdo, priorizando os dados mais atuais "
    "e mais relevantes a respeito do conteúdo",
    agent = tutor,
    expected_output = "Deve entregar um resumo para o usuário com a seguinte estrutura: visão geral e exemplos úteis de uso do {conteudo} "
    "de modo que seja didático e dinâmico, sem supor informações sobre o {conteudo} "
    "Resumo não deve conter mais que 200 palavras"
)

# Criação da tarefa do agente Monitor, responsável por fornecer materiais complementares a respeito do conteúdo em questão
selecao_materiais = Task(
    name = "Buscar e fornecer para o usuário materiais de estudo relevantes sobre o {conteudo}",
    description = "Buscar materiais de suporte sobre o {conteudo} que facilitem o aprendizado do usuário, como vídeos e plataformas relevantes a respeito do {conteudo} "
    "Encontrar os mateirias que se adequam mais ao {conteudo}, utilizando como base os dados obtidos pelo tutor",
    agent = monitor,
    expected_output = "Deve entregar uma representação textual em formato de tópicos para o usuário contendo os materiais mais relevantes, em formato de links para páginas de internet "
    "Listar, em média, 10 links, sendo eles: sites, vídeos, artigos e imagens "
    "de modo que seja dinâmico, sem supor informações sobre o {conteudo}"
)

# Criação da tarefa do agente Instrutor, responsável por criar os exercícios
criar_exercicios = Task(
    name = "Criar exercícios para facilitar o entendimento do usuário a respeito do {conteudo}",
    description = "Gerar exercícios cont4xtualizados sobre o {conteudo}, de modo que seja possível aprimorar as habilidades e facilitar o aprendizado "
    "Faça questão de fornecer elementos simples mas que encapsulam bem o assunto, e aumentar, gradativamente, o nível de dificuldade dos exercícios "
    "Usar como base o resumo feito pelo tutor e os materiais selecionados pelo monitor",
    agent = instrutor,
    expected_output = "Deve entregar uma representação textual em formato de uma lista de exercícios para o usuário sobre o {conteudo} "
    "Deve criar em média 8 exercícios contextualizados sobre o assunto, aumentando gradativamente o nível de dificuldade ",
)

# Criação da tarefa do agente Consultor, responsável por fornecer as respostas dos exercícios propostos
gabarito = Task(
    name = "Fornecer o gabarito dos exercícios propostos pelo agente Instrutor a respeito do contéudo: {conteudo} ",
    description = "Responder de forma correta os exerícios propostos para que o usuário tenha uma forma de conferir se sua linha de raciocínio está correta ao respeito do tópico ou deseja "
    "apenas conferir as suas respostas"
    "Usar como base o resumo feito pelo tutor, os materiais selecionados pelo monitor para responder os exercícios feitos pelo instrutor",
    agent = consultor,
    expected_output = "Deve entregar uma representação textual em formato de gabraito de uma lista de exercícios para o usuário sobre o {conteudo} "
    "Deve conter as respostas de forma detalhada para facilitar o entendimento do usuário"
    "Deve ser entregue após um minuto após o envio das perguntas"
)

# Criação da equipe/sistema multiagente
equipe = Crew(
    agents = [tutor, monitor, instrutor, consultor],
    tasks = [resumir, selecao_materiais, criar_exercicios, gabarito],
)

# Execução
def menu():
  print("---------------------------------------------")
  print("🤖 Seja bem-vindo ao Tutor Inteligente! 🤖")
  print("---------------------------------------------")
  print("Como podemos lhe ajudar hoje?\n")
  conteudo = input("Qual o tópico que você tem dificuldade?\n\n -> ")
  entradas = {'conteudo': conteudo}

  print("\n----------------------------------------------")
  print(f"Processando sua dúvida sobre {conteudo}...")
  print("----------------------------------------------\n")

  saida = equipe.kickoff(inputs=entradas)
  resultado = saida.tasks_output
  for r in resultado:
    print(r)

  print("\nObrigada por utilizar o Tutor Inteligente! 🤖")

menu()

menu()

menu()

menu()

